"""Command line wrapper generator for lm_memories."""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Iterable


RAM_PORTS = (
  "crw_crw",
  "rw_rw",
  "cr_cw",
  "cr_cw_ratio",
  "crw_cr",
  "crw_cw",
  "r_w",
  "r_w_ratio",
)

VENDORS = ("generic", "xilinx", "amd", "intel", "altera", "lattice", "microchip", "microsemi")
STYLES = ("auto", "distributed", "bram", "uram", "registers")
MODES = ("generic", "fixed")


def _positive_int(value: str) -> int:
  parsed = int(value, 10)
  if parsed <= 0:
    raise argparse.ArgumentTypeError("value must be positive")
  return parsed


def _latency(value: str) -> int:
  parsed = _positive_int(value)
  if parsed not in (1, 2):
    raise argparse.ArgumentTypeError("latency must be 1 or 2")
  return parsed


def _is_power_of_two(value: int) -> bool:
  return value > 0 and (value & (value - 1)) == 0


def _entity_name(path: Path) -> str:
  name = re.sub(r"[^a-z0-9_]+", "_", path.stem.lower()).strip("_")
  if not name:
    name = "lm_mem_generated"
  if name[0].isdigit():
    name = "lm_" + name
  return name


def _write(path: Path, text: str) -> None:
  path.parent.mkdir(parents=True, exist_ok=True)
  path.write_text(text, encoding="utf-8")


def _header(module_name: str, description: str) -> str:
  return f"""--=============================================================================
-- Module Name : {module_name}
-- Library     : -
-- Project     : lm_memories
-- Company     : LogiMentor Srl
-------------------------------------------------------------------------------
-- Description:
--  {description}
--  Generated by lm_memgen. Edit the generator inputs rather than this wrapper.
-------------------------------------------------------------------------------
"""


def _generic_block(mode: str, lines: Iterable[str]) -> str:
  if mode != "generic":
    return ""

  joined = ";\n".join(f"    {line}" for line in lines)
  return f"  generic(\n{joined}\n  );\n"


def _ram_expr(args: argparse.Namespace) -> dict[str, str]:
  width_b = args.width_b if args.width_b is not None else args.width_a
  if args.mode == "generic":
    return {
      "width_a": "g_width_a",
      "width_b": "g_width_b",
      "depth_a": "g_depth_a",
      "latency_a": "g_read_latency_a",
      "latency_b": "g_read_latency_b",
    }

  return {
    "width_a": str(args.width_a),
    "width_b": str(width_b),
    "depth_a": str(args.depth_a),
    "latency_a": str(args.read_latency_a),
    "latency_b": str(args.read_latency_b),
  }


def _addr_a(expr: dict[str, str]) -> str:
  return f"f_ceil_log2({expr['depth_a']}) - 1 downto 0"


def _addr_b_ratio(expr: dict[str, str]) -> str:
  return f"f_ceil_log2(({expr['depth_a']} * {expr['width_a']}) / {expr['width_b']}) - 1 downto 0"


def _ram_port_block(ports: str, expr: dict[str, str]) -> str:
  width = expr["width_a"]
  width_b = expr["width_b"]

  if ports == "crw_crw":
    return f"""  port(
    clk_a_i     : in  std_logic;
    clk_b_i     : in  std_logic;
    ena_i       : in  std_logic := '1';
    enb_i       : in  std_logic := '1';
    wen_a_i     : in  std_logic;
    wen_b_i     : in  std_logic;
    data_wr_a_i : in  std_logic_vector({width} - 1 downto 0);
    data_wr_b_i : in  std_logic_vector({width_b} - 1 downto 0);
    addr_a_i    : in  std_logic_vector({_addr_a(expr)});
    addr_b_i    : in  std_logic_vector({_addr_b_ratio(expr)});
    data_rd_a_o : out std_logic_vector({width} - 1 downto 0);
    data_rd_b_o : out std_logic_vector({width_b} - 1 downto 0)
  );
"""

  if ports == "rw_rw":
    return f"""  port(
    clk_i      : in  std_logic;
    ena_i      : in  std_logic := '1';
    enb_i      : in  std_logic := '1';
    wen_a_i    : in  std_logic;
    wen_b_i    : in  std_logic;
    wr_dat_a_i : in  std_logic_vector({width} - 1 downto 0);
    wr_dat_b_i : in  std_logic_vector({width} - 1 downto 0);
    addr_a_i   : in  std_logic_vector({_addr_a(expr)});
    addr_b_i   : in  std_logic_vector({_addr_a(expr)});
    rd_dat_a_o : out std_logic_vector({width} - 1 downto 0);
    rd_dat_b_o : out std_logic_vector({width} - 1 downto 0)
  );
"""

  if ports in ("cr_cw", "cr_cw_ratio"):
    rd_width = width_b if ports.endswith("_ratio") else width
    rd_addr = _addr_b_ratio(expr) if ports.endswith("_ratio") else _addr_a(expr)
    return f"""  port(
    wr_clk_i  : in  std_logic;
    rd_clk_i  : in  std_logic;
    ena_i     : in  std_logic := '1';
    enb_i     : in  std_logic := '1';
    wen_i     : in  std_logic;
    wr_addr_i : in  std_logic_vector({_addr_a(expr)});
    wr_dat_i  : in  std_logic_vector({width} - 1 downto 0);
    rd_addr_i : in  std_logic_vector({rd_addr});
    rd_dat_o  : out std_logic_vector({rd_width} - 1 downto 0)
  );
"""

  if ports == "crw_cr":
    return f"""  port(
    clk_a_i     : in  std_logic;
    clk_b_i     : in  std_logic;
    ena_i       : in  std_logic := '1';
    enb_i       : in  std_logic := '1';
    wen_a_i     : in  std_logic;
    data_wr_a_i : in  std_logic_vector({width} - 1 downto 0);
    addr_a_i    : in  std_logic_vector({_addr_a(expr)});
    addr_b_i    : in  std_logic_vector({_addr_a(expr)});
    data_rd_a_o : out std_logic_vector({width} - 1 downto 0);
    data_rd_b_o : out std_logic_vector({width} - 1 downto 0)
  );
"""

  if ports == "crw_cw":
    return f"""  port(
    clk_a_i     : in  std_logic;
    clk_b_i     : in  std_logic;
    ena_i       : in  std_logic := '1';
    enb_i       : in  std_logic := '1';
    wen_a_i     : in  std_logic;
    wen_b_i     : in  std_logic;
    data_wr_a_i : in  std_logic_vector({width} - 1 downto 0);
    data_wr_b_i : in  std_logic_vector({width} - 1 downto 0);
    addr_a_i    : in  std_logic_vector({_addr_a(expr)});
    addr_b_i    : in  std_logic_vector({_addr_a(expr)});
    data_rd_a_o : out std_logic_vector({width} - 1 downto 0)
  );
"""

  rd_width = width_b if ports == "r_w_ratio" else width
  rd_addr = _addr_b_ratio(expr) if ports == "r_w_ratio" else _addr_a(expr)
  return f"""  port(
    clk_i     : in  std_logic;
    ena_i     : in  std_logic := '1';
    enb_i     : in  std_logic := '1';
    wen_i     : in  std_logic;
    wr_addr_i : in  std_logic_vector({_addr_a(expr)});
    wr_dat_i  : in  std_logic_vector({width} - 1 downto 0);
    rd_addr_i : in  std_logic_vector({rd_addr});
    rd_dat_o  : out std_logic_vector({rd_width} - 1 downto 0)
  );
"""


def _ram_instance(ports: str, expr: dict[str, str]) -> str:
  module = f"lm_mem_ram_{ports}"
  width = expr["width_a"]
  width_b = expr["width_b"]
  depth = expr["depth_a"]
  latency_a = expr["latency_a"]
  latency_b = expr["latency_b"]

  if ports in ("crw_crw", "cr_cw_ratio", "r_w_ratio"):
    generic_map = f"""      g_ram_a_latency => {latency_a},
      g_ram_a_data_w  => {width},
      g_ram_a_depth   => {depth},
      g_ram_b_latency => {latency_b},
      g_ram_b_data_w  => {width_b},
      g_init_file     => "",
      g_simulation    => 1"""
  else:
    generic_map = f"""      g_ram_latency => {latency_a},
      g_ram_data_w  => {width},
      g_ram_depth   => {depth},
      g_init_file   => "",
      g_simulation  => 1"""

  port_map = {
    "crw_crw": """      clk_a_i     => clk_a_i,
      clk_b_i     => clk_b_i,
      ena_i       => ena_i,
      enb_i       => enb_i,
      wen_a_i     => wen_a_i,
      wen_b_i     => wen_b_i,
      data_wr_a_i => data_wr_a_i,
      data_wr_b_i => data_wr_b_i,
      addr_a_i    => addr_a_i,
      addr_b_i    => addr_b_i,
      data_rd_a_o => data_rd_a_o,
      data_rd_b_o => data_rd_b_o""",
    "rw_rw": """      clk_i      => clk_i,
      ena_i      => ena_i,
      enb_i      => enb_i,
      wen_a_i    => wen_a_i,
      wen_b_i    => wen_b_i,
      wr_dat_a_i => wr_dat_a_i,
      wr_dat_b_i => wr_dat_b_i,
      addr_a_i   => addr_a_i,
      addr_b_i   => addr_b_i,
      rd_dat_a_o => rd_dat_a_o,
      rd_dat_b_o => rd_dat_b_o""",
    "cr_cw": """      wr_clk_i  => wr_clk_i,
      rd_clk_i  => rd_clk_i,
      ena_i     => ena_i,
      enb_i     => enb_i,
      wen_i     => wen_i,
      wr_addr_i => wr_addr_i,
      wr_dat_i  => wr_dat_i,
      rd_addr_i => rd_addr_i,
      rd_dat_o  => rd_dat_o""",
    "cr_cw_ratio": """      wr_clk_i  => wr_clk_i,
      rd_clk_i  => rd_clk_i,
      ena_i     => ena_i,
      enb_i     => enb_i,
      wen_i     => wen_i,
      wr_addr_i => wr_addr_i,
      wr_dat_i  => wr_dat_i,
      rd_addr_i => rd_addr_i,
      rd_dat_o  => rd_dat_o""",
    "crw_cr": """      clk_a_i     => clk_a_i,
      clk_b_i     => clk_b_i,
      ena_i       => ena_i,
      enb_i       => enb_i,
      wen_a_i     => wen_a_i,
      data_wr_a_i => data_wr_a_i,
      addr_a_i    => addr_a_i,
      addr_b_i    => addr_b_i,
      data_rd_a_o => data_rd_a_o,
      data_rd_b_o => data_rd_b_o""",
    "crw_cw": """      clk_a_i     => clk_a_i,
      clk_b_i     => clk_b_i,
      ena_i       => ena_i,
      enb_i       => enb_i,
      wen_a_i     => wen_a_i,
      wen_b_i     => wen_b_i,
      data_wr_a_i => data_wr_a_i,
      data_wr_b_i => data_wr_b_i,
      addr_a_i    => addr_a_i,
      addr_b_i    => addr_b_i,
      data_rd_a_o => data_rd_a_o""",
    "r_w": """      clk_i     => clk_i,
      ena_i     => ena_i,
      enb_i     => enb_i,
      wen_i     => wen_i,
      wr_addr_i => wr_addr_i,
      wr_dat_i  => wr_dat_i,
      rd_addr_i => rd_addr_i,
      rd_dat_o  => rd_dat_o""",
    "r_w_ratio": """      clk_i     => clk_i,
      ena_i     => ena_i,
      enb_i     => enb_i,
      wen_i     => wen_i,
      wr_addr_i => wr_addr_i,
      wr_dat_i  => wr_dat_i,
      rd_addr_i => rd_addr_i,
      rd_dat_o  => rd_dat_o""",
  }[ports]

  return f"""  inst_mem : entity work.{module}
    generic map(
{generic_map}
    )
    port map(
{port_map}
    );
"""


def _validate_ram(args: argparse.Namespace, parser: argparse.ArgumentParser) -> None:
  width_b = args.width_b if args.width_b is not None else args.width_a
  min_width = min(args.width_a, width_b)
  max_width = max(args.width_a, width_b)
  ratio_ports = {"crw_crw", "cr_cw_ratio", "r_w_ratio"}

  if max_width % min_width != 0:
    parser.error("--width-a and --width-b must have an integer ratio")
  if (args.depth_a * args.width_a) % width_b != 0:
    parser.error("--depth-a * --width-a must divide cleanly by --width-b")
  if args.ports not in ratio_ports and width_b != args.width_a:
    parser.error(f"--ports {args.ports} requires --width-b to match --width-a")
  if args.ports not in ratio_ports and args.read_latency_b != args.read_latency_a:
    parser.error(f"--ports {args.ports} uses one latency; set both read latencies equal")


def _render_ram(args: argparse.Namespace) -> str:
  out = Path(args.out)
  entity = _entity_name(out)
  expr = _ram_expr(args)
  width_b = args.width_b if args.width_b is not None else args.width_a
  generic_lines = (
    f"g_width_a        : positive := {args.width_a}",
    f"g_depth_a        : positive := {args.depth_a}",
    f"g_width_b        : positive := {width_b}",
    f"g_read_latency_a : positive := {args.read_latency_a}",
    f"g_read_latency_b : positive := {args.read_latency_b}",
  )

  return (
    _header(entity, f"Wrapper around lm_mem_ram_{args.ports}.")
    + "\nlibrary ieee;\nuse ieee.std_logic_1164.all;\n\nuse work.lm_mem_pkg.all;\n\n"
    + f"entity {entity} is\n"
    + _generic_block(args.mode, generic_lines)
    + _ram_port_block(args.ports, expr)
    + f"end entity {entity};\n\n"
    + f"architecture a_rtl of {entity} is\n"
    + "begin\n"
    + _ram_instance(args.ports, expr)
    + "end architecture a_rtl;\n"
  )


def _render_fifo(args: argparse.Namespace) -> str:
  out = Path(args.out)
  entity = _entity_name(out)
  if args.mode == "generic":
    width = "g_width"
    depth = "g_depth"
    generic = _generic_block(
      args.mode,
      (
        f"g_width : positive := {args.width}",
        f"g_depth : positive := {args.depth}",
      ),
    )
  else:
    width = str(args.width)
    depth = str(args.depth)
    generic = ""

  return f"""{_header(entity, "Wrapper around lm_mem_fifo_sync.")}
library ieee;
use ieee.std_logic_1164.all;

entity {entity} is
{generic}  port(
    clk_i          : in  std_logic;
    rst_n_i        : in  std_logic;
    din_i          : in  std_logic_vector({width} - 1 downto 0);
    wen_i          : in  std_logic;
    ren_i          : in  std_logic;
    dout_o         : out std_logic_vector({width} - 1 downto 0);
    full_o         : out std_logic;
    almost_full_o  : out std_logic;
    empty_o        : out std_logic;
    almost_empty_o : out std_logic;
    valid_o        : out std_logic
  );
end entity {entity};

architecture a_rtl of {entity} is
begin
  inst_fifo : entity work.lm_mem_fifo_sync
    generic map(
      g_data_w             => {width},
      g_depth              => {depth},
      g_almost_empty_limit => 1,
      g_almost_full_limit  => 1
    )
    port map(
      clk_i          => clk_i,
      rst_n_i        => rst_n_i,
      din_i          => din_i,
      wen_i          => wen_i,
      ren_i          => ren_i,
      dout_o         => dout_o,
      full_o         => full_o,
      almost_full_o  => almost_full_o,
      empty_o        => empty_o,
      almost_empty_o => almost_empty_o,
      valid_o        => valid_o
    );
end architecture a_rtl;
"""


def _add_ram_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
  parser = subparsers.add_parser("ram", help="emit a RAM wrapper")
  parser.add_argument("--ports", choices=RAM_PORTS, required=True, help="RAM port topology")
  parser.add_argument("--vendor", choices=VENDORS, default="generic", help="target vendor annotation")
  parser.add_argument("--family", default="generic", help="target family annotation")
  parser.add_argument("--tool", default="generic", help="target synthesis tool annotation")
  parser.add_argument("--width-a", type=_positive_int, required=True, help="port A data width")
  parser.add_argument("--depth-a", type=_positive_int, required=True, help="port A depth")
  parser.add_argument("--width-b", type=_positive_int, help="port B data width")
  parser.add_argument("--read-latency-a", type=_latency, default=1, help="port A read latency")
  parser.add_argument("--read-latency-b", type=_latency, default=1, help="port B read latency")
  parser.add_argument("--style", choices=STYLES, default="auto", help="requested memory style annotation")
  parser.add_argument("--mode", choices=MODES, default="generic", help="wrapper generation mode")
  parser.add_argument("--out", required=True, help="output VHDL file")
  parser.set_defaults(func=_run_ram, parser=parser)


def _add_fifo_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
  parser = subparsers.add_parser("fifo", help="emit a FIFO wrapper")
  parser.add_argument("--vendor", choices=VENDORS, default="generic", help="target vendor annotation")
  parser.add_argument("--width", type=_positive_int, required=True, help="FIFO data width")
  parser.add_argument("--depth", type=_positive_int, required=True, help="FIFO depth")
  parser.add_argument("--clocking", choices=("sync",), default="sync", help="FIFO clocking mode")
  parser.add_argument("--mode", choices=MODES, default="generic", help="wrapper generation mode")
  parser.add_argument("--out", required=True, help="output VHDL file")
  parser.set_defaults(func=_run_fifo, parser=parser)


def _run_ram(args: argparse.Namespace) -> int:
  _validate_ram(args, args.parser)
  _write(Path(args.out), _render_ram(args))
  return 0


def _run_fifo(args: argparse.Namespace) -> int:
  if not _is_power_of_two(args.depth):
    args.parser.error("--depth must be a power of two for lm_mem_fifo_sync")
  _write(Path(args.out), _render_fifo(args))
  return 0


def build_parser() -> argparse.ArgumentParser:
  parser = argparse.ArgumentParser(
    prog="lm_memgen",
    description="Generate lm_memories VHDL wrappers.",
  )
  subparsers = parser.add_subparsers(dest="command", required=True)
  _add_ram_parser(subparsers)
  _add_fifo_parser(subparsers)
  return parser


def main(argv: list[str] | None = None) -> int:
  parser = build_parser()
  args = parser.parse_args(argv)
  return args.func(args)
