-- SPDX-License-Identifier: Apache-2.0
-- Copyright 2026 LogiMentor Srl
--=============================================================================
-- Module Name : lm_fifo_async_example
-- Library     : -
-- Project     : lm_memories
-- Company     : LogiMentor Srl
-------------------------------------------------------------------------------
-- Description:
--  Wrapper around lm_mem_fifo_async.
--  Generated by lm_memgen. Edit the generator inputs rather than this wrapper.
-------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;

entity lm_fifo_async_example is
  generic(
    g_width : positive := 32;
    g_depth : positive := 1024
  );
  port(
    wr_clk_i       : in  std_logic;
    wr_rst_n_i     : in  std_logic;
    rd_clk_i       : in  std_logic;
    rd_rst_n_i     : in  std_logic;
    din_i          : in  std_logic_vector(g_width - 1 downto 0);
    wen_i          : in  std_logic;
    ren_i          : in  std_logic;
    dout_o         : out std_logic_vector(g_width - 1 downto 0);
    full_o         : out std_logic;
    almost_full_o  : out std_logic;
    empty_o        : out std_logic;
    almost_empty_o : out std_logic;
    valid_o        : out std_logic
  );
end entity lm_fifo_async_example;

architecture a_rtl of lm_fifo_async_example is
begin
  inst_fifo : entity work.lm_mem_fifo_async
    generic map(
      g_data_w             => g_width,
      g_depth              => g_depth,
      g_almost_empty_limit => 1,
      g_almost_full_limit  => 1
    )
    port map(
      wr_clk_i       => wr_clk_i,
      wr_rst_n_i     => wr_rst_n_i,
      rd_clk_i       => rd_clk_i,
      rd_rst_n_i     => rd_rst_n_i,
      din_i          => din_i,
      wen_i          => wen_i,
      ren_i          => ren_i,
      dout_o         => dout_o,
      full_o         => full_o,
      almost_full_o  => almost_full_o,
      empty_o        => empty_o,
      almost_empty_o => almost_empty_o,
      valid_o        => valid_o
    );
end architecture a_rtl;
