-- SPDX-License-Identifier: Apache-2.0
-- Copyright 2026 LogiMentor Srl
--=============================================================================
-- Module Name : lm_mem_example
-- Library     : -
-- Project     : lm_memories
-- Company     : LogiMentor Srl
-------------------------------------------------------------------------------
-- Description:
--  Wrapper around lm_mem_ram_crw_crw.
--  Generated by lm_memgen. Edit the generator inputs rather than this wrapper.
-------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;

use work.lm_mem_pkg.all;

entity lm_mem_example is
  generic(
    g_width_a        : positive := 32;
    g_depth_a        : positive := 1024;
    g_width_b        : positive := 8;
    g_read_latency_a : positive := 1;
    g_read_latency_b : positive := 1
  );
  port(
    clk_a_i     : in  std_logic;
    clk_b_i     : in  std_logic;
    ena_i       : in  std_logic := '1';
    enb_i       : in  std_logic := '1';
    wen_a_i     : in  std_logic;
    wen_b_i     : in  std_logic;
    data_wr_a_i : in  std_logic_vector(g_width_a - 1 downto 0);
    data_wr_b_i : in  std_logic_vector(g_width_b - 1 downto 0);
    addr_a_i    : in  std_logic_vector(f_ceil_log2(g_depth_a) - 1 downto 0);
    addr_b_i    : in  std_logic_vector(f_ceil_log2((g_depth_a * g_width_a) / g_width_b) - 1 downto 0);
    data_rd_a_o : out std_logic_vector(g_width_a - 1 downto 0);
    data_rd_b_o : out std_logic_vector(g_width_b - 1 downto 0)
  );
end entity lm_mem_example;

architecture a_rtl of lm_mem_example is
begin
  inst_mem : entity work.lm_mem_ram_crw_crw
    generic map(
      g_ram_a_latency => g_read_latency_a,
      g_ram_a_data_w  => g_width_a,
      g_ram_a_depth   => g_depth_a,
      g_ram_b_latency => g_read_latency_b,
      g_ram_b_data_w  => g_width_b,
      g_init_file     => "",
      g_simulation    => 1
    )
    port map(
      clk_a_i     => clk_a_i,
      clk_b_i     => clk_b_i,
      ena_i       => ena_i,
      enb_i       => enb_i,
      wen_a_i     => wen_a_i,
      wen_b_i     => wen_b_i,
      data_wr_a_i => data_wr_a_i,
      data_wr_b_i => data_wr_b_i,
      addr_a_i    => addr_a_i,
      addr_b_i    => addr_b_i,
      data_rd_a_o => data_rd_a_o,
      data_rd_b_o => data_rd_b_o
    );
end architecture a_rtl;
